version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-vikunja}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-vikunja}
      POSTGRES_DB: ${POSTGRES_DB:-vikunja}
    volumes:
      - vikunja-db:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    restart: unless-stopped

  vikunja:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RELEASE_VERSION: local
    depends_on:
      - db
    ports:
      - "3456:3456"
    environment:
      # database
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_HOST: db:5432
      VIKUNJA_DATABASE_USER: ${POSTGRES_USER:-vikunja}
      VIKUNJA_DATABASE_PASS: ${POSTGRES_PASSWORD:-vikunja}
      VIKUNJA_DATABASE_NAME: ${POSTGRES_DB:-vikunja}
      # service
      VIKUNJA_SERVICE_ROOTPATH: /app/vikunja/
      # optional: change to sqlite for a single-file DB
      # VIKUNJA_DATABASE_TYPE: sqlite
      # VIKUNJA_DATABASE_PATH: /db/vikunja.db
    volumes:
      - vikunja-storage:/db
    restart: unless-stopped

volumes:
  vikunja-db:
  vikunja-storage:
